apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mykubernate-90b1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mykubernate-90b1"
  template:
    metadata:
      labels:
        app: "mykubernate-90b1"
    spec:
      containers:
        - name: "mykubernate-90b1"
          image: "myreg2020.azurecr.io/mykubernate"
          ports:
          - containerPort: 9999